#!/bin/bash

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --name multi-arch-builder --use
docker buildx inspect --bootstrap
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 -f $DOCKERFILE_PATH -t $IMAGE_NAME --push .
